### ISSUE TITLE
Backend menu not woking

### ISSUE THREAD

**Issue by bachlee89** [unirgy/convertm1m2#10]
I have converted our BannerSlider to M2, I saw Banner Slider in backend menu but it not working. It rediect to dashboard.

**Comment by unirgy** [comment]
Please note that the script will not produce a ready to run code. It is made to save a developer time by performing repetitive tasks that can be easily automated. 

You would still need to learn M2, go file by file and fix things manually.

**Comment by bachlee89** [comment]
Hi, Thank for your update.
