### ISSUE TITLE
Incorrectly Converts `class` attribute of system.xml tabs node

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#12]
I passed an extension through this program whose system.xml contained the following ("foo" used to be the extension name, changes since this is a private/commercial project)

	<tabs>
		<foo translate="label" module="foo">
			<label>Foo (1.15.4)</label>
			<sort_order>151</sort_order>
			<class>foo</class>
		</foo>
	</tabs>

Magento 2 rejected the new system.xml with the following error

    Invalid XML in file /path/to/magento2/app/code/Foo/Foo/etc/adminhtml/system.xml:
    Element 'class': This element is not expected. Expected is ( label ).
    Line: 5

I'm not sure what the `class` node did in Magento 1 (if anything), but it would be nice if the conversion scripts created the appropriate new nodes in Magento 2, or did something smarter about porting over nodes that aren't a part of the schema.

**Comment by unirgy** [comment]
Fix pushed, please check

**Comment by astorm** [comment]
Thanks for the fix!

I don't have a great test harness setup for this and I'm in the middle of converting an extension (i.e. time constrained and can't afford to move my work out of the way to try reconverting).  Let's close it for now, and I've got a reminder setup to come back and test it when some time frees up.
