### ISSUE TITLE
Class Conversion and PHP keywords

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#13]
I used this script to convert an extension, and that extension contained a class with the following name

    Foo_Bar_Model_System_Config_Source_Header_Usermenu_Break_Position

This script tried to create a new class

    Foo\Bar\Model\System\Config\Source\Header\Usermenu\Break\Position;

Unfortunately, `Break` is a PHP keyword, and this ended up creating an invalid namespace.

    namespace Infortis\Ultimo\Model\System\Config\Source\Header\Usermenu\Break;

which PHP couldn't handle

    Parse error: syntax error, unexpected 'Break' (T_BREAK), expecting identifier (T_STRING) in

It would be nice if the script could be smarter about not using PHP keywords as class names (i.e. automatically convert them).

**Comment by astorm** [comment]
List of keywords 

http://php.net/manual/en/reserved.keywords.php

and reserved words

http://php.net/manual/en/reserved.other-reserved-words.php

**Comment by unirgy** [comment]
Would adding "1" to the keyword be ok?

**Comment by unirgy** [comment]
Never mind, implemented using the previous word as suffix

**Comment by unirgy** [comment]
Fix pushed, please check

**Comment by astorm** [comment]
Thanks for the fix -- either one works OK (unless you have a secret PHP based API that can rename based on context (-: )

I don't have a great test harness setup for this and I'm in the middle of converting an extension (i.e. time constrained and can't afford to move my work out of the way to try reconverting).  Let's close it for now, and I've got a reminder setup to come back and test it when some time frees up.
