### ISSUE TITLE
Class Magento\Backend\Model\System\Config\Backend\Image does not exist

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#14]
If the conversion script encounter the following node in a `system.xml` file

    <backend_model>adminhtml/system_config_backend_image</backend_model>

If converts it to 

    <backend_model>Magento\Backend\Model\System\Config\Backend\Image</backend_model>

There is no such model `Magento\Backend\Model\System\Config\Backend\Image` in Magento 2, and PHP lets you know

    Class Magento\Backend\Model\System\Config\Backend\Image does not exist
    #0 /Users/alanstorm/Sites/magento-2-with-keys/magento2/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Backend...')
    #1 /Users/alanstorm/Sites/magento-2-with-keys/magento2/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Backend...')

**Comment by astorm** [comment]
The correct class **may** be `Magento\Config\Model\Config\Backend\Image`

    $ find . -name system.xml | xargs ack 'backend_model.+?Image'
    vendor/magento/module-backend/etc/adminhtml/system.xml
    217:                    <backend_model>Magento\Config\Model\Config\Backend\Image\Adapter</backend_model>

    vendor/magento/module-catalog/etc/adminhtml/system.xml
    94:                    <backend_model>Magento\Config\Model\Config\Backend\Image</backend_model>
    164:                    <backend_model>Magento\Config\Model\Config\Backend\Image</backend_model>

    vendor/magento/module-sales/etc/adminhtml/system.xml
    55:                    <backend_model>Magento\Config\Model\Config\Backend\Image\Pdf</backend_model>
    64:                    <backend_model>Magento\Config\Model\Config\Backend\Image</backend_model>

    vendor/magento/module-theme/etc/adminhtml/system.xml
    16:                    <backend_model>Magento\Config\Model\Config\Backend\Image\Favicon</backend_model>
    65:                    <backend_model>Magento\Config\Model\Config\Backend\Image\Logo</backend_model

but it's hard to tell -- it's a little unclear if Magento 2 wants you using generic classes here, or a specific class for each config.

**Comment by unirgy** [comment]
Added conversion:
`Mage_Adminhtml_Model_System_Config_Backend_` => `Magento_Config_Model_Config_Backend_`

**Comment by unirgy** [comment]
Fix pushed, please check

**Comment by astorm** [comment]
Thanks for the fix!

I don't have a great test harness setup for this and I'm in the middle of converting an extension (i.e. time constrained and can't afford to move my work out of the way to try reconverting).  Let's close it for now, and I've got a reminder setup to come back and test it when some time frees up.
