### ISSUE TITLE
Observer Conversion Incomplete

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#15]
I have a module with the following observer declared.

    <controller_action_postdispatch_adminhtml_system_config_save>
        <observers>
            <foobaz>
                <type>singleton</type>
                <class>foobaz/observer</class>
                <method>hookTo_controllerActionPostdispatchAdminhtmlSystemConfigSave</method>
            </foobaz>
        </observers>
    </controller_action_postdispatch_adminhtml_system_config_save>

The conversion script converts this to the following XML

    <event name="controller_action_postdispatch_adminhtml_system_config_save">
        <observer name="ultimo" instance="Foo\Baz\Model\Observer\HookToControllerActionPostdispatchAdminhtmlSystemConfigSave"/>
    </event>

This is good, since Magento 2 moved to a "one method per observer" model in the final release.

However, the conversion script **does not** create the `HookToControllerActionPostdispatchAdminhtmlSystemConfigSave` class, which leads to the following error.

    Class Foo\Baz\Model\Observer\HookToControllerActionPostdispatchAdminhtmlSystemConfigSave does not exist

It would be nice if the conversion script generated a class with an execute method that injected the original observer object, and called the original method.

**Comment by unirgy** [comment]
Ah, it does split the observer, but puts directly under module root, not in Model. Fixing events.xml

**Comment by unirgy** [comment]
Fix pushed, please check

**Comment by astorm** [comment]
Thanks for the fix!

I don't have a great test harness setup for this and I'm in the middle of converting an extension (i.e. time constrained and can't afford to move my work out of the way to try reconverting).  Let's close it for now, and I've got a reminder setup to come back and test it when some time frees up.

**Comment by astorm** [comment]
Re-opening this for a related issue.  One of the generated observer classes didn't have an `execute` method defined in it.  I'll attempt to find time to recreate a test case (unless you can think of a reason this wouldn't happen)

**Comment by unirgy** [comment]
Please reopen when you have isolated test case, i didn't see this happening. Thanks
