### ISSUE TITLE
Do Something Smart with Mage:: Calls

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#16]
After converting, many classes are left with calls to the old static helper

    Mage::app()->getConfig
    Mage::app()->getLayout
    Mage::app()->getWebsite
    Mage::app()->getWebsites
    Mage::getBaseDir
    Mage::getConfig
    Mage::getModel
    Mage::getSingleton
    Mage::getStoreConfig
    Mage::getUrl
    Mage::helper
    Mage::log

While 100% coverage would be impossible, it'd be nice if some of these were converted to their Magento 2 equivalents.

**Comment by unirgy** [comment]
`Mage::log`, `Mage::helper`, `Mage::getSingleton`, `Mage::getModel`, `Mage::getStoreConfig` should be fully covered.
`Mage::app()->getConfig` calls were split to multiple classes, some of them handled.

Could you please give examples of not converted code with these?

**Comment by astorm** [comment]
There were `Mage::log` calls in the setup resource data scripts (`data/foobar_setup/data-*.php`).
There were `Mage::getSingleton ` calls in the setup resource data scripts (`data/foobar_setup/data-*.php`).
There were `Mage::getModel` calls in the  setup resource data scripts (`data/foobar_setup/data-*.php`).
There were `Mage::getStoreConfig` calls in the setup resource data scripts  (`data/foobar_setup/data-*.php`).

There were `Mage::helper` calls in 

    app/code/Foo/Baz/Helper/Header.php
    app/code/Foo/Baz/Helper/Template/Page/Html/Header.php
    app/code/Foo/Baz/Helper/Data

These calls took the form 

    return Mage::helper($this->_menuModuleNameShort)->getMobileMenuThreshold();
    return Mage::helper($this->_menuModuleNameShort)->getMobileMenuThreshold();
    $theme = Mage::helper($packageName);
    $theme = Mage::helper($packageName);

Some `Mage::app()` calls that wern't converted.

    $now = strtotime(Mage::app()->getLocale()->date()->setTime('00:00:00')->toString(Date::DATETIME_INTERNAL_FORMAT));
    $websites = Mage::app()->getWebsites(false, true); //IMPORTANT: without admin website. Get websites by code.
    Mage::app()->getConfig()->reinit();

**Comment by unirgy** [comment]
Thank you for details. The problem with variables in `Mage::helper($var)` is that it is impossible to convert them directly to class names as in case of static references `Mage::helper('core/data')`.

Using `ObjectManager::getInstance()->get($var)` will not really fix anything because `$var` is generated not as class name but Magento1 alias.

**Comment by unirgy** [comment]
All other cases handled in latest commit

**Comment by unirgy** [comment]
Closing this and other issues, please reopen if there's a problem.
