### ISSUE TITLE
Injected Dependencies in CRUD Models

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#17]
When converting a Magento "CRUD" model (a model that extends the `Magento\Framework\Model\AbstractModel` base abstract class), the conversion script produced a constructor that looked like this

	public function __construct(Context $context, 
        Registry $registry, 
        AbstractResource $resource = null, 
        AbstractDb $resourceCollection = null, 
        array $data = [], 
        Cssgen $helperCssgen = null, 
        StoreManagerInterface $modelStoreManagerInterface = null, 
        ManagerInterface $messageManagerInterface = null, 
        LoggerInterface $logLoggerInterface = null)
    {
        $this->_helperCssgen = $helperCssgen;
        $this->_modelStoreManagerInterface = $modelStoreManagerInterface;
        $this->_messageManagerInterface = $messageManagerInterface;
        $this->_logLoggerInterface = $logLoggerInterface;

        parent::__construct($context, $registry, $resource, $resourceCollection, $data);
		//$this->_cssDir = $this->_helperCssgen->getGeneratedCssDir();
    }

By giving the new di parameters (`Cssgen $helperCssgen = null, StoreManagerInterface $modelStoreManagerInterface = null, ManagerInterface $messageManagerInterface = null, LoggerInterface $logLoggerInterface = null`) a default value of `null`, the parameters are not injected into the class.  

However, removing the `null`

        StoreManagerInterface $modelStoreManagerInterface, 
        ManagerInterface $messageManagerInterface, 

results in the the following error

> Fatal error: Cannot instantiate abstract class Magento\Framework\Model\ResourceModel\AbstractResource

Question: What's the reasoning behind defaulting all the DI parameters to `null`.  Am I missing a use case where these are properly injected?

Feature Request: Is there something more intelligent we could do here for the CRUD models? I've got [an open stack exchange question](http://magento.stackexchange.com/questions/96752/injecting-dependencies-into-a-magento-2-crud-abstract-model) to see if anyone has a solution and/or if those abstract parameters can be safely ignored.

**Comment by unirgy** [comment]
The converter takes constructor arguements from parent class, and adds any other deps used in current class on top of them. If parent class constructor had optional arguments, the newly added arguments should be optional as well. 

Apparently, M2 doesn't handle well optional class arguments. Did you try moving the new arguments before optional arguments of parent class? If that works, I'll try to change the logic to inject new arguments this way.

**Comment by astorm** [comment]
@unirgy Per that stack exchange question I did try that, and moving the class in front of those optional parameters allowed an object to be instantiated (i.e. the dependency was injected, but Magento skipped trying to inject the abstract ones)

Based on [this answer](http://magento.stackexchange.com/a/96754/4) it sounds like Magento themselves are doing this for their CRUD models so *it seems* like it would be safe for the script to do it.

**Comment by unirgy** [comment]
Please see if the last commit fixes this
