### ISSUE TITLE
Conversion of Code that Uses Layout Singleton

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#18]
Is there anything the script could do to convert code like the following

			$output = Mage::app()->getLayout()
				->createBlock("core/template")
				->setData('area', 'frontend')
				->setTemplate($templatePath)
				->toHtml();

The script converts the above to the following

			$output = Mage::app()->getLayout()
				->createBlock("Magento\Framework\View\Element\Template")
				->setData('area', 'frontend')
				->setTemplate($templatePath)
				->toHtml();

Maybe an injected `Magento\Framework\View\Layout` to replace `Mage::app()->getLayout`?

**Comment by unirgy** [comment]
Not sure if that will cover all cases, but added in last commit

**Comment by unirgy** [comment]
I'm also not sure which one should be used:
`'Mage::app()->getLayout()' => self::OBJ_MGR . '(\'Magento\Framework\View\Layout\')',`
`self::OBJ_MGR . '(\'Magento\Framework\View\LayoutFactory\')->create()',`

**Comment by astorm** [comment]
Yeah, I can definitely see this not handling all cases -- to much has changed in the layout system.

**Comment by unirgy** [comment]
Closing for now
