### ISSUE TITLE
The `__` function is not sprintf compatible. 

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#19]
The conversion script converts code like 

     Mage::helper('module')->__("Template file is empty or doesn't exist: %s", $templatePath)

into 

    __("Template file is empty or doesn't exist: %s", $templatePath);

This is good!  However, the new global gettext style `__` is **not** `sprintf`compatible.  It's a numeric based replacment. The above should actually be

    __("Template file is empty or doesn't exist: %1", $templatePath);

It would be great if the script could catch and convert these.   If you or the googler who finds this in 6 months is curious , the replacement seems to happen here

    vendor/magento/framework/Phrase/Renderer/Placeholder.php

**Comment by unirgy** [comment]
Done
