### ISSUE TITLE
No `frontend_model`s in `system.xml` Were Converted

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#20]
The module doesn't seem to convert the `frontend_model` nodes in `system.xml` files.  Unless there's a compelling reason not to, it would be useful if these nodes were converted automatically.

i.e. the following node

    <heading_link translate="label">
        <label>Link</label>
        <frontend_model>adminhtml/system_config_form_field_heading</frontend_model>
        <sort_order>199</sort_order>
        <show_in_default>1</show_in_default>
        <show_in_website>1</show_in_website>
        <show_in_store>1</show_in_store>
    </heading_link>

was converted into.

    <field id="heading_link" translate="label" sortOrder="199" showInDefault="1" showInWebsite="1" showInStore="1">
      <label>Link</label>
    </field>

It woul

**Comment by unirgy** [comment]
Fixed, thanks
