### ISSUE TITLE
Error Creating Base Abstract Controller

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#21]
When the module split the following controller (altered slightly to preserver anonymity) into a base abstract controller

    <?php
    class Vendor_Modulename_Adminhtml_modulenameController extends Mage_Adminhtml_Controller_Action
    {
        protected $_helper;
        protected $_hc; /*OBFFROM: $_helpermodulename */
        protected $_ep; /*OBFFROM: $_eventPrefix */

        /*OBF: protected $_helper; protected $_hc; protected $_ep; */

        /**
         * Resource initialization
         */
        protected function _construct()
        {
            $this->_helper 			= Mage::helper("Modulename");
            $this->_hc 				= Mage::helper("Modulename/modulename_data");
            $this->_ep				= "Modulename_modulename";
        }

        protected function _isAllowed()
        {
            return Mage::getSingleton('admin/session')->isAllowed('Modulename');
        }

        /**
         * View form action
         *
         * @return void
         */
        public function indexAction()
        {
            //Check requested action type
            $actionType = $this->getRequest()->getParam("action_type");
            if ($actionType === "export")
            {
                $block = $this->getLayout()->createBlock("Modulename/adminhtml_modulename_export_edit");
            }
            elseif ($actionType === "import")
            {
                $block = $this->getLayout()->createBlock("Modulename/adminhtml_modulename_import_edit");
            }
            elseif ($actionType === NULL)
            {
                $this->getResponse()->setRedirect($this->getUrl("adminhtml/dashboard"));
                return;
            }

            $this->loadLayout();
            $this->_setActiveMenu('Vendor');
            $this->_addBreadcrumb($this->_helper->__("Config Import and Export"), $this->_helper->__("Config Import and Export"));

            ///$this->_debugInfo(__FUNCTION__);
            $this->_addContent($block);

            $this->renderLayout();
        }

        ////////////////////////////////////////////////////////////////////////////////////////////////////////
        // Export
        ////////////////////////////////////////////////////////////////////////////////////////////////////////

        /**
         * Export action
         *
         * @return void
         */
        public function exportAction()
        {
            $this->loadLayout();
            ///$this->_debugInfo(__FUNCTION__);

            //Get list of modules to export
            $modules = $this->_getModulesToExport();
            if (!empty($modules))
            {
                try
                {
                    //Get file to save config presets
                    $file = $this->_getExportFile();
                    $this->_createExportDir($file);

                    //Important: for export the scope should be provided as store id - single value, not an array
                    $store = $this->getRequest()->getParam("stores");
                    if (is_array($store))
                    {
                        throw new Exception("Website/Store ID retrieved as array. Expected string.");
                    }

                    $this->_export($modules, "default", $store, $file);

                    Mage::getSingleton("adminhtml/session")->addSuccess(
                        $this->_helper->__("Successfully exported to file %s", $file)
                    );
                }
                catch (Exception $e)
                {
                    Mage::logException($e);
                    Mage::getSingleton("adminhtml/session")->addError(
                        $this->_helper->__("An error occurred during export to file %s", $file)
                        . "<br/>" .
                        $this->_helper->__("Exception: %s", $e->getMessage())
                    );
                } //end: try-catch
            }
            else
            {
                Mage::getSingleton("adminhtml/session")->addError(
                    $this->_helper->__("An error occurred: no source module selected for export.")
                );
            }

            $this->renderLayout();
            $this->getResponse()->setRedirect($this->getUrl("*/*/", $this->_getControlParams()));
        } //end: exportAction

        /**
         * Get file to save config presets
         *
         * @return string
         */
        protected function _getExportFile()
        {
            return $this->_hc->getPresetFilepath(
                $this->getRequest()->getParam("preset_name"),
                $this->getRequest()->getParam("package")
            );
        }

        /**
         * Check if directory of the file path exists and is writable. If not, create writable directory.
         *
         * @param string
         * @return bool
         */
        protected function _createExportDir($filepath)
        {
            $mode = 0777;
            $dir = dirname($filepath);

            if (is_dir($dir))
            {
                //If directory not writable, change mode
                if (!is_writable($dir))
                {
                    chmod($dir, $mode);
                }
            }
            else //Directory doesn't exist
            {
                //Create directory
                if (!mkdir($dir, $mode, true))
                {
                    //Unable to create directory.
                    return FALSE;
                }
            }

            return TRUE;
        }

        /**
         * Get modules associated with package
         *
         * @return array
         */
        protected function _getModulesToExport()
        {
            //Get (from the form) list of modules to export
            $retrievedModules = $this->getRequest()->getParam("modules");

            //Get rid of empty names
            $modules = array();
            if (!empty($retrievedModules))
            {
                foreach ($retrievedModules as $mod)
                {
                    if (!empty($mod))
                    {
                        $modules[] = $mod;
                    }
                }
            }
            return $modules;
        }

        ////////////////////////////////////////////////////////////////////////////////////////////////////////
        // Import
        ////////////////////////////////////////////////////////////////////////////////////////////////////////

        /**
         * Import action
         *
         * @return void
         */
        public function importAction()
        {
            $this->loadLayout();
            ///$this->_debugInfo(__FUNCTION__);

            //Get path of file with saved config
            $file = $this->_getImportFile();

            if (file_exists($file))
            {
                try
                {
                    $store = $this->getRequest()->getParam("stores");

                    //Decode scope
                    $scope = Mage::getSingleton("Vendor/config_scope")->decodeScope($store);

                    //Import
                    $importParam = "vasbegvf";
                    $this->_import($scope["scope"], $scope["scopeId"], $file);

                    //Success message
                    Mage::getSingleton("adminhtml/session")->addSuccess(
                        $this->_helper->__("Successfully imported from file %s", $file)
                    );

                    //Dispatch event: Modulename_modulename_import_after
                    $eventParams = array("portScope" => $scope["scope"], "portScopeId" => $scope["scopeId"]);
                    Mage::dispatchEvent($this->_ep . "_import_after", $eventParams);
                }
                catch (Exception $e)
                {
                    Mage::logException($e);
                    Mage::getSingleton("adminhtml/session")->addError(
                        $this->_helper->__("An error occurred during import from file %s", $file)
                        . "<br/>" .
                        $this->_helper->__("Exception: %s", $e->getMessage())
                    );
                } //end: try-catch
            }
            else
            {
                Mage::getSingleton("adminhtml/session")->addError(
                    $this->_helper->__("An error occurred: unable to read file %s", $file)
                );
            }

            $this->renderLayout();
            $this->getResponse()->setRedirect($this->getUrl("*/*/", $this->_getControlParams()));
        } //end: importAction

        /**
         * Get file path with saved configuration.
         * File can be uploaded via the form or retrieved from predefined folder of the package (main module in the package)
         *
         * @return string
         */
        protected function _getImportFile()
        {
            //Desitnation directory for files uploaded via form
            $tmpFileBaseDir = $this->_helper->getTmpFileBaseDir();
            $uploadedFileName = '';
            $resultFile = '';

            if (!empty($_FILES["data_import_file"]["name"])) //File was selected in the form
            {
                ///Mage::log('_getImportFile() -- data: ' . print_r($this->getRequest()->getPost(), 1), null, 'Modulename.txt'); ///
                ///Mage::log('_getImportFile() -- _FILES: ' . print_r($_FILES, 1), null, 'Modulename.txt'); ///
                if (file_exists($_FILES["data_import_file"]["tmp_name"])) //File successfully uploaded to temporary directory
                {
                    try
                    {
                        $uploader = new Varien_File_Uploader("data_import_file");
                        $uploader->setAllowedExtensions(array('xml'));
                        $uploader->setAllowCreateFolders(true);
                        $uploader->setAllowRenameFiles(false);
                        $uploader->setFilesDispersion(false);
                    
                        $uploader->save($tmpFileBaseDir, $_FILES["data_import_file"]["name"]);
                        $resultFile = $tmpFileBaseDir . $_FILES["data_import_file"]["name"];
                    }
                    catch(Exception $e)
                    {
                        Mage::getSingleton("adminhtml/session")->addError(
                            $this->_helper->__("An error occurred during upload of file %s", $_FILES["data_import_file"]["name"])
                            . "<br/>" .
                            $this->_helper->__("Exception: %s", $e->getMessage())
                        );
                    } //end: try-catch
                }
            }
            else //File NOT selected in the form
            {
                $resultFile = $this->_hc->getPresetFilepath(
                    $this->getRequest()->getParam("preset_name"),
                    $this->getRequest()->getParam("package")
                );
            }

            if (!empty($resultFile))
            {
                return $resultFile;
            }
            else
            {
                return '';
            }
        }

        ////////////////////////////////////////////////////////////////////////////////////////////////////////
        // Helper methods
        ////////////////////////////////////////////////////////////////////////////////////////////////////////

        /**
         * Get control parameters
         *
         * @return array
         */
        protected function _getControlParams()
        {
            $params = array();
            $params["action_type"] = $this->getRequest()->getParam("action_type");
            $params["package"] = $this->getRequest()->getParam("package");
            return $params;
        }

        /**
         * Print and log debug info
         *
         * @return void
         */
        protected function _debugInfo($here)
        {
            $data = print_r($this->getRequest()->getParams(), 1);
            Mage::log("Here: " . $here . " :\n" . $data, null, "Modulename.log");

            $output  = "<pre>" . $here . " :\n";
            $output .= $data;
            $output .= "</pre>";
            $block = $this->getLayout()->createBlock("core/text", "debug-data-print")->setText($output);
            $this->_addContent($block);
        }

        ////////////////////////////////////////////////////////////////////////////////////////////////////////
        // Import/Export data
        ////////////////////////////////////////////////////////////////////////////////////////////////////////

        /**
         * Export configuration (by node specified in $path param) from config.xml file of modules
         * and save it in a file
         *
         * @param array
         * @param string $path Node of configuration XML which contains settings to export
         * @param string
         * @param string
         * @param bool
         * @param bool
         * @return void
         */
        protected function _export($modules, $path, $store, $filepath, $flag_ifOptionNullReplaceWithDefaultConfig=TRUE, $flag_ifDefaultConfigNullOmit = FALSE)
        {
            ///Mage::log('_export: ' . implode(':', $modules) .' + '. $path .' + '. $store .' + '. $filepath); ///

            //Get root node
            $rootNode = $this->_getModulesConfigDefaultValues($modules, $path);
            $nodesToRemove = array();

            foreach ($rootNode->children() as $section)
            {
                ///Mage::log($section->getName());
                foreach ($section->children() as $group)
                {
                    ///Mage::log('-- ' . $group->getName());
                    foreach ($group->children() as $option)
                    {
                        //IMPORTANT: omit this node if it has deeper levels
                        if ($option->hasChildren())
                        {
                            ///Mage::log('---- ---- omit, this node has children: ' . $option->getName() . ' ==> ...'); ///
                            continue; //Omit this node
                        }

                        //$section->getName() . '/' . $group->getName() . '/' . $option->getName()
                        $optionPath = $section->getName() . '/' . $group->getName() . '/' . $option->getName();
                        $valueFromConfig = Mage::getStoreConfig(
                            $optionPath,
                            $store
                        );
                        ///Mage::log('---- ' . $option->getName() . ' ===>' . $valueFromConfig);

                        //Check additional constraints ONLY if export is for store view and not for the Default Config
                        //and if option value is NULL (after retrieving from db it's an empty string)
                        if ($store > 0 && '' === $valueFromConfig)
                        {
                            if ($flag_ifOptionNullReplaceWithDefaultConfig)
                            {
                                //Get option value from Default Config
                                $valueFromConfig_DEFAULT = Mage::getStoreConfig(
                                    $optionPath,
                                    0
                                );

                                //If Default Config option value is not NULL, export it instead of option value
                                $valueFromConfig = $valueFromConfig_DEFAULT;
                                ///Mage::log('     NULL, replace with Default=' . $valueFromConfig_DEFAULT); ///

                                if ($flag_ifDefaultConfigNullOmit)
                                {
                                    if ('' === $valueFromConfig_DEFAULT)
                                    {
                                        //If Default Config option value is NULL too, omit this node and don't export.
                                        //So the node has to be removed from the main XML object.
                                        ///Mage::log('     value from Default also NULL. Remove this path: '.$optionPath); ///
                                        $nodesToRemove[] = $optionPath;
                                        continue;
                                    }
                                }
                            }
                        }

                        //Add exported value to the XML
                        $group->{$option->getName()} = $valueFromConfig;

                    } //end: foreach
                } //end: foreach
            } //end: foreach

            //Remove nodes selected to be removed
            foreach ($nodesToRemove as $nodePath)
            {
                $node = $rootNode->xpath($nodePath);
                unset($node[0][0]);
            }

            //Save
            $niceXml = $rootNode->asNiceXml();
            if (!file_put_contents($filepath, $niceXml))
            {
                throw new Exception("Unable to write file.");
            }
        }

        /**
         * Get and collect configuration (by node specified in $path param) of all specified modules
         *
         * @param array
         * @param string
         * @return Varien_Simplexml_Element
         */
        protected function _getModulesConfigDefaultValues($modules, $path)
        {
            $rootXml = simplexml_load_string("<defaul></defaul>", "Varien_Simplexml_Element");
            //$rootXml = new Varien_Simplexml_Element("<defaul></defaul>");
            foreach ($modules as $module)
            {
                //Get config nodes matching the path.
                //Nodes are inside the main node which is named the same as path.
                $node = $this->_getModuleConfig($module, $path);

                if ($node && ($node instanceof SimpleXMLElement))
                {
                    //Get children of the main node and append them to the container node
                    foreach ($node->children() as $child)
                    {
                        $rootXml->appendChild($child);
                    }
                }
            }

            return $rootXml;
        }

        /**
         * Get configuration of selected module
         *
         * @param array
         * @param string
         * @return Varien_Simplexml_Element
         */
        protected function _getModuleConfig($module, $path)
        {
            $configFile = Mage::getConfig()->getModuleDir("etc", $module) . DS . "config.xml";

            //If file (and module) exists
            if (file_exists($configFile))
            {
                $content = file_get_contents($configFile);

                //If file content successfully retrieved
                if ($content !== FALSE)
                {
                    $xml = simplexml_load_string($content, "Varien_Simplexml_Element");

                    //Get selected node
                    $node = $xml->descend($path);
                    return $node;
                }
            }

            return NULL;
        }

        ////////////////////////////////////////////////////////////////////////////////////////////////////////

        /**
         * Import configuration from a file and save all config values in database for specified scope and store
         *
         * @param string
         * @param int
         * @param string
         * @return void
         */
        protected function _import($scope, $scopeId, $filepath)
        {
            //Get root node
            $rootNode = $this->_getXmlFromFile($filepath);
            if (!$rootNode)
            {
                throw new Exception("Unable to read XML data from file - empty file or invalid format.");
            }

            ///Mage::log('-- import scope: ' . $scope .' + '. $scopeId);
            foreach ($rootNode->children() as $section)
            {
                ///Mage::log($section->getName());
                foreach ($section->children() as $group)
                {
                    ///Mage::log('-- ' . $group->getName());
                    foreach ($group->children() as $option)
                    {
                        ///Mage::log('-- import to: ' . $section->getName() . '/' . $group->getName() . '/' . $option->getName() . ' <==' . $option);

                        //IMPORTANT: omit this node if it has deeper levels
                        if ($option->hasChildren())
                        {
                            ///Mage::log('---- omit, this node has children: ' . $option->getName() . ' ==> ...'); ///
                            continue;
                        }

                        //If option value is NULL (after retrieving it's an empty string), then import NULL
                        $optionValue = (string) $option;
                        if ('' === $optionValue)
                        {
                            $optionValue = NULL;
                        }
                    
                        //Save option value in config
                        Mage::getConfig()->saveConfig(
                            $section->getName() . '/' . $group->getName() . '/' . $option->getName(),
                            $optionValue,
                            $scope,
                            $scopeId
                        );

                    }
                }
            } //end: foreach
        }

        /**
         * Get XML data from a file and load it as XML object
         *
         * @param string
         * @return Varien_Simplexml_Element
         */
        protected function _getXmlFromFile($file)
        {
            $content = file_get_contents($file);
            return simplexml_load_string($content, "Varien_Simplexml_Element");
        }
    }

The resulting `AbstractCfgporter` had the following invalid code inside of it.

	protected function _isAllowed()
	{
		return $this->_authorization->isAllowed('dataporter');
	}

	////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Export
	////////////////////////////////////////////////////////////////////////////////////////////////////////

		$this->renderLayout();
		$this->getResponse()->setRedirect($this->getUrl("*/*/", $this->_getControlParams()));
	} //end: exportAction

	/**
	 * Get file to save config presets
	 *
	 * @return string
	 */
	protected function _getExportFile()
	{
		return $this->_hc->getPresetFilepath(
			$this->getRequest()->getParam("preset_name"),
			$this->getRequest()->getParam("package")
		);
	}
	
It would be great if the parsing code could be tightened up so this didn't happen in the future.

**Comment by unirgy** [comment]
Thank you, fixed
