### ISSUE TITLE
Convert also adminhtml design templates located in app/design/adminhtml/base/default folder

### ISSUE THREAD

**Issue by kypfr** [unirgy/convertm1m2#26]
Hello Unirgy,

Thanks for your convertion tool. It help me earn time during this conversion step.
Most of my designs for the adminhtml are located in the app/design/adminhtml/base/default to be leave them work fine even if back-office use a custom design.
Your tool does not convert them (you check only default/default). Can you also add this folder in those your script look for?
Regards

Matthieu

**Comment by unirgy** [comment]
Thank you, this has been added, please check

**Comment by kypfr** [comment]
Not for now. But I thinks this is a typo in your commit:

`$this->convertLayoutAreaTheme('adminhtml', 'adminhtml/base');`
I think it should be:
`$this->convertLayoutAreaTheme('adminhtml', 'base/default');`

Regards

**Comment by unirgy** [comment]
You're right. It's 1:15am here, I should probably go to sleep :) Please test

**Comment by kypfr** [comment]
it's fine, thanks you!
