### ISSUE TITLE
Convert references to block instanceof core/block_list in referenceContainer

### ISSUE THREAD

**Issue by kypfr** [unirgy/convertm1m2#27]
Hello Unirgy,

After migrate my layouts, in my M1 layouts, I've many blocks which are containers for others blocks.
These blocks are instanceof Mage_Core_Block_Text_List.
But references to these blocks are convert within your script into &lt;reference&gt; and not &lt;referenceContainer&gt;, the new syntax for these containers.
If referenced block is an instance of Mage_Core_Block_Text_List, it could be interesting to use the new reference node, don't you think?

**Comment by unirgy** [comment]
There's actually logic for this (line 1663):

```
if (is_subclass_of($className, 'Mage_Core_Block_Text_List') || $nodeName === 'content') {
   $targetChildXml = $targetXml->addChild('referenceContainer');
} else {
   $targetChildXml = $targetXml->addChild('reference');
}
```
You're saying it's not working properly?

**Comment by unirgy** [comment]
Please check if this is fixed, thanks.

**Comment by kypfr** [comment]
Even after upgrade no:

Take the following example with 2 modules:
I have a Magento 1 layout file module.xml which contains:
`<block type="moduleid/core_text_list" name="my_block_name"/>`
which reference to: 
`class Kyp_ModuleId_Block_Core_Text_List extends Mage_Core_Block_Text_List`
and a second module magento 1 with the following layout xml content:
`<reference name="my_block_name">`
the generated layout after conversion of the module 2 contains:
`<reference name="my_block_name"></reference>`

Regards

**Comment by unirgy** [comment]
Could you please test the latest commit? thanks!

**Comment by kypfr** [comment]
No. No worries.
I'll try to check your convert.php script with some logs to be more verbose and provide you more details.
Regards

**Comment by unirgy** [comment]
Please reopen when you have a reproducible case. Thanks
