### ISSUE TITLE
requirejs instructions added into templates does not take care of CDATA instructions

### ISSUE THREAD

**Issue by kypfr** [unirgy/convertm1m2#28]
Hello unirgy,

After converting my m1 templates into m2 templates, I've seen that you add the requirejs instruction.
Ex for a M1 template:
`...
<script type="text/javascript">
...
</script>`
is converted into:
`...
<script type="text/javascript">
require(["jquery", "prototype"], function(jQuery) {
...
});
</script>`

But if there is a CDATA tag into the template used,
`...
<script type="text/javascript">
//<![CDATA[
...
 //]]>
</script>`
the converted template is:
`...
<script type="text/javascript">
require(["jquery", "prototype"], function(jQuery) {
//<![CDATA[
...
 //]]>
});
</script>`

it should be:
`...
<script type="text/javascript">
//<![CDATA[
require(["jquery", "prototype"], function(jQuery) {
...
});
 //]]>
</script>`

regards

**Comment by unirgy** [comment]
Please check if this is fixed, thanks.

**Comment by kypfr** [comment]
Yes, thanks!
