### ISSUE TITLE
Require instruction are not removed after converting to Magento2

### ISSUE THREAD

**Issue by kypfr** [unirgy/convertm1m2#30]
Hello Unirgy,

Some controllers depends in Magento1 of a controller which cannot be loaded with autoload.
To load this parent controller, the appropriate syntax is:
`require_once Mage::getModuleDir('controllers', 'Namespace_Module') . DS . 'FooController.php';`
These instructions are still existing after converting the controller.
They should be removed because they will be loaded in another syntax.

**Comment by unirgy** [comment]
Ok, so i'll be removing only this pattern: `require_once Mage::getModuleDir('controllers', 'Namespace_Module') . DS . 'FooController.php';` ?

**Comment by kypfr** [comment]
Hello,

This pattern is when the best practices are applied.
But by experience, many users does not take care of the compilation feature and load the required controller with a syntax like the following one:
`require_once BP.DS.'app'.DS.'code.'codepool'.DS....Controller.php`

I think a good pattern could be:
`require(_once)? .+Controller.php['"]`

regards

**Comment by unirgy** [comment]
Fixed
