### ISSUE TITLE
Interface conversion seems not fine

### ISSUE THREAD

**Issue by kypfr** [unirgy/convertm1m2#31]
Hello Unirgy,

I'm using in some M1 modules interfaces.
It seems that conversion is not fine. For example for a M1 interface:
`interface Kyp_ModuleId_Model_Something_Interface`
the code content generated into the M2 module is:
`interface \Kyp\ModuleId\Model\SomethingInterface
{...}`

Methods in M2 interface are fine, but It seems that code content should be:
`namespace Kyp\ModuleId\Model\
interface SomethingInterface 
{...}`

Regards

**Comment by unirgy** [comment]
Should there be some code after your sentence: "Methods in M2 interface are fine, but It seems that code content should be:" ? Doesn't show for me

**Comment by kypfr** [comment]
Sorry, it was a typo in my post, it was late when I wrote it and I was tired :)
I've updated my post.
