### ISSUE TITLE
Initiate requirejs-config.js with loaded javascript files in layouts

### ISSUE THREAD

**Issue by kypfr** [unirgy/convertm1m2#32]
Hello Unirgy,

I know it's quite a bit difficult to understand relationship which exists between javascript files and so build automatically the dependencies for require-js, but it could be interesting for huge project to initiate the requirejs-config.js file with loaded javascript file in layouts in the differents context
``var config {
         'map': 
                * {
           ...
}
}
`
This feature is not required, but can help to earn time in the post processing updates.

Regards

**Comment by unirgy** [comment]
I think I'll opt for a pull request for this feature :)
