### ISSUE TITLE
command runs, but nothing happens

### ISSUE THREAD

**Issue by GerbenBergman** [unirgy/convertm1m2#33]
Hi,

I have followed the instructions in the readme file, but when i run this command:
![image](https://cloud.githubusercontent.com/assets/10921106/14679421/130d8dc6-071a-11e6-8a59-e779aa90cc40.png)
nothing happens in the magento 2 directory. Also I couldn't understand all the instructions, if anyone could make an instruction video it would be very helpfull.

thanks,

Gerben

**Comment by unirgy** [comment]
Hi Gerben, did you add full code of extensions that you want to convert to `convertm1m2-master/source` folder?

**Comment by GerbenBergman** [comment]
Hi unirgy,

I added this files to the convertm1m2-master:

convertm1m2-master/magento (the magento 1 package with the extension i want to convert in app/code/community/VendorName/ExtensionName)

convertm1m2-master/Magento2 (the magento 2 package)

convertm1m2-master/source (where i have my extension in /vendorName/ExtensionName)

**Comment by GerbenBergman** [comment]
Can someone please tell me what I am doing wrong?

**Comment by tinelps** [comment]
is the problem solved? @GerbenBergman
