### ISSUE TITLE
Problems with ALLCAP_Module name modules. 

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#40]
The conversion script seems to have trouble with modules that use a `ALLCAPS_Modulename` naming scheme.

    app/code/local/ALLCAPS/Modulename

For example, the following controller file

    <?php
    class FOO_Module_TestController extends Mage_Contacts_IndexController
    {
        public function indexAction(){
        }
    }

Get converted into an abstract controller file that looks like this

    <?php
    class FOO_\Module\Controller\Test\AbstractTest extends 
    \Magento\Contacts\Controller\Index\AbstractIndex
    {
    }

In addition to converting this class incorrectly, this also might interfere with method parsing on controller classes which, in turn, interferes with controller creation.  bout to issue a pull request that demonstrates this via a test case.

**Comment by astorm** [comment]
Pull request demonstrating problem cases is here: https://github.com/unirgy/convertm1m2/pull/41

**Comment by astorm** [comment]
Thanks @unirgy -- looks like that did the trick!  My real controllers are now converting.    

Quick question -- what's the 

    $contents = preg_replace_callback('#(.)([A-Z][A-Za-z0-9]+_[A-Za-z0-9_]+_[A-Za-z0-9_])#'

regular expression meant to match?

**Comment by unirgy** [comment]
// Convert any left underscored class names to backslashed. If class name is in string value, don't prefix

the first dot to match a potential (double)quote, the rest is to match old style class names.
