### ISSUE TITLE
module.xml created without setup_version attribute

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#43]
This program creates a `module.xml` file similar to the following

    <?xml version="1.0"?>
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
      <module name="PACKAGE_Module"/>
    </config>
    
That is, its missing the `setup_module` version number

    <?xml version="1.0"?>
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
      <module name="PACKAGE_Module" setup_version="0.0.1"/>
    </config>
     
This attribute's required, and Magento's CLI will crash without it there.

**Comment by unirgy** [comment]
I can not reproduce this issue on my modules, could you please paste the relevant part of the original config.xml ?

This file is generated by `convertConfigModule` method, this is the respondible code:
```
        if (!empty($xml1->modules->{$extName}->version)) {
            $targetXml->addAttribute('setup_version', (string)$xml1->modules->{$extName}->version);
        }
```

**Comment by astorm** [comment]
Ah, I think I see the problem here.  I was converting a module named similar to `ABC_Contacts`.  However, its config.xml looked like 

    <modules>
        <ABC_Customer>
            <version>1.0.0</version>
        </ABC_Customer>
    </modules>

That is -- it had the wrong module name.  Surprised this worked at all.  

Two ways of handling this

1. Since we (should?) know the module name, if its missing halt and/or sending a warning flag
2. Since `setup_version` is required, if we don't find an existing module name in the config, then use something like `1.0.0` as a default.

**Comment by unirgy** [comment]
Is it required even if there are no migrations?

**Comment by astorm** [comment]
Yup -- wouldn't have bothered otherwise.  

Yup -- wouldn't have bothered otherwise.  

    $ pestle_dev magento2:generate:module
    Vendor Namespace? (Pulsestorm)] 
    Module Name? (Testbed)] Isitrequiredeveniftherearenomigrations
    Version? (0.0.1)] 
    Created: /path/to/magento/app/code/Pulsestorm/Isitrequiredeveniftherearenomigrations/etc/module.xml
    Created: /path/to/magento/app/code/Pulsestorm/Isitrequiredeveniftherearenomigrations/registration.php

Edit `app/code/Pulsestorm/Isitrequiredeveniftherearenomigrations/etc/module.xml` to remove the `setup_version` attribute.

    <?xml version="1.0"?>
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
        <module name="Pulsestorm_Isitrequiredeveniftherearenomigrations" />
    </config>

Try to enable module
    
    $ php bin/magento module:enable Pulsestorm_Isitrequiredeveniftherearenomigrations
                                                        
    [InvalidArgumentException]                                
    There are no commands defined in the "module" namespace.  
                                                            
What?  Try to list commands

    $ php bin/magento 

    Magento CLI version 2.1.3

    Usage:
     command [options] [arguments]

    Options:
     --help (-h)           Display this help message
     --quiet (-q)          Do not output any message
     --verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
     --version (-V)        Display this application version
     --ansi                Force ANSI output
     --no-ansi             Disable ANSI output
     --no-interaction (-n) Do not ask any interactive question

    Available commands:
     help   Displays help for a command
     list   Lists commands
    We're sorry, an error occurred. Try clearing the cache and code generation directories. By default, they are: var/cache, var/di, var/generation, and var/page_cache.

                                                             
      [Zend\ServiceManager\Exception\ServiceNotCreatedException]                   
      An abstract factory could not create an instance of magentosetupconsolecomm  
      andconfigsetcommand(alias: Magento\Setup\Console\Command\ConfigSetCommand).  
                                                                               
      [Zend\ServiceManager\Exception\ServiceNotCreatedException]                   
      An exception was raised while creating "Magento\Setup\Console\Command\Confi  
      gSetCommand"; no instance returned                                           
                                                                               
      [Exception]                                                                  
      Attribute 'setup_version' is missing for module 'Pulsestorm_Isitrequiredeve  
      niftherearenomigrations'.                                                    

Notice last exception --                                                                                

> Attribute 'setup_version' is missing for module 'Pulsestorm\_Isitrequiredeveniftherearenomigrations'.

**Comment by unirgy** [comment]
Added a warning
