### ISSUE TITLE
extDir preg_match condition issue

### ISSUE THREAD

**Issue by Krupaly2k** [unirgy/convertm1m2#46]
Hi,

I have configured the extension but facing some issue in this. I have configured with below details:

1. I have created source folder in same directory and added module named ModuleA in that added files like app/code/community/, skin folder etc.
2. In m1 I have set my magento 1 directory path
3. In m2 I have set magento2 directory path.

Now, the issue i am facing it is not going beyond below condition. I am always getting $m array as blank

           if (!preg_match('#^(.*)/([A-Za-z0-9]+_[A-Za-z0-9]+)$#', $extDir, $m)) {
				
                continue;
            } 

Please guide me for the next step.

Thanks in advance!

**Comment by unirgy** [comment]
The folder name under `source` folder should have a format like `Namespace_Module`, sounds like you have only `ModuleA`

**Comment by Krupaly2k** [comment]
Thanks for your quick response. I have tried to change the name with Abc_Test like that as well but it doesn't work.

**Comment by unirgy** [comment]
does it proceed after the preg_match test?

**Comment by Krupaly2k** [comment]
It is not going beyond below condition
 if (!preg_match('#^(.*)/([A-Za-z0-9]+_[A-Za-z0-9]+)$#', $extDir, $m)) {
				
                continue;
            }

**Comment by unirgy** [comment]
could you post a screenshot of your folder structure?

**Comment by Krupaly2k** [comment]
![magento1_and_magento2](https://user-images.githubusercontent.com/1654278/29159980-214a4362-7dce-11e7-8b15-1a333d805140.png)
![1](https://user-images.githubusercontent.com/1654278/29159979-21381b4c-7dce-11e7-961f-f4a1ef646c9b.png)
![2](https://user-images.githubusercontent.com/1654278/29159981-214c62c8-7dce-11e7-92fb-d9390bc426ee.png)
![3](https://user-images.githubusercontent.com/1654278/29159982-214e02e0-7dce-11e7-86f4-c340f850d8f9.png)

**Comment by unirgy** [comment]
and what's the command with arguments you're running?

**Comment by Krupaly2k** [comment]
I am running from web

**Comment by Krupaly2k** [comment]
/convertm1m2-master/convert.php

**Comment by unirgy** [comment]
should be working, can you add this debug output and paste what you're getting:

        // AFTER:
        $extDirs = glob($this->_env['source_dir'] . '/*', GLOB_ONLYDIR);
        // ADD THIS:
        var_dump($this->_env['source_dir'], $extDirs);

**Comment by Krupaly2k** [comment]
It is showing below result

string(32) "source/Calrion_Customerattribute"
array(2) {
  [0]=>
  string(36) "source/Calrion_Customerattribute/app"
  [1]=>
  string(37) "source/Calrion_Customerattribute/skin"
}

**Comment by unirgy** [comment]
did you change `convert.php` or `ConvertM1M2.php` before that? looks like `source_dir` is not correct. When running from web it should always be just `source`, you can see it in `convert.php`

**Comment by Krupaly2k** [comment]
Ok. My convert.php is as given below:

 $sourceDir = 'source/Calrion_Customerattribute';
    $mage1Dir = '../magento181/';
    $mage2Dir = '../mag4/';
    $stage = !empty($_GET['a']) ? (int)$_GET['a'] : 1;

**Comment by unirgy** [comment]
restore: `$sourceDir = 'source';`

**Comment by Krupaly2k** [comment]
Yes, I have changed that and it is working now. Thanks for your quick help!
