### ISSUE TITLE
After Conversion module not working in m2 issue

### ISSUE THREAD

**Issue by Krupaly2k** [unirgy/convertm1m2#47]
Hi Boris,

The extension is really good. I have converted one M1 customer attribute extension which is displaying in my M2 / app/code/ folder but it is showing only etc, composer and registration file. controller and model files are missing in that.

Please guide me on that how can i resolve this issue.

Thanks in advance!

**Comment by unirgy** [comment]
Is there extension open source? If you can send it to me I can try to figure out the issue

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Krupaly2k** [comment]
Sure.

**Comment by unirgy** [comment]
you can send to unirgy at gmail

**Comment by Krupaly2k** [comment]
Thanks

**Comment by Krupaly2k** [comment]
unirgy@gmail.com right?

**Comment by unirgy** [comment]
yes, but i'd prefer not to have as it on too many public pages to decrease spam

**Comment by Krupaly2k** [comment]
https://www.magentocommerce.com/magento-connect/manage-customer-attributes-1.html 

Try this one. I am trying to convert this extension. Thanks for your quick response

**Comment by unirgy** [comment]
if you could send me the package, it would be great

**Comment by Krupaly2k** [comment]
Ok, at which email address should I have to send you?

**Comment by unirgy** [comment]
the one you asked about

**Comment by Krupaly2k** [comment]
[Clarion_Customerattribute-1.0.2 (2).zip](https://github.com/unirgy/convertm1m2/files/1214289/Clarion_Customerattribute-1.0.2.2.zip)

**Comment by unirgy** [comment]
It converted properly for me: 

http://i.imgur.com/VrqBDOX.png

http://i.imgur.com/ytybeze.png

Do you have the extension installed in your magento1 folder?

**Comment by Krupaly2k** [comment]
Yes, It is installed

**Comment by unirgy** [comment]
paste the conversion process log

**Comment by Krupaly2k** [comment]
Ok, I am getting error here Notice:  Undefined variable: m in C:\xampp\htdocs\convertm1m2-master\ConvertM1M2.php on line 395

in this line if ($folders && preg_match('#app/code/(core|community|local)/#', $folders[0], $m)) {

**Comment by unirgy** [comment]
for me this is on line 378. this error doesn't make sense because $m is write only variable in this context

**Comment by Krupaly2k** [comment]
![5](https://user-images.githubusercontent.com/1654278/29163938-9080e846-7ddb-11e7-883c-23abe18e416c.png)

**Comment by unirgy** [comment]
it should be Clarion, not Calrion...

**Comment by Krupaly2k** [comment]
Ok, Great. Now it is working fine! Thanks again and sorry for the silly mistake

**Comment by unirgy** [comment]
Great

**Comment by unirgy** [comment]
please note, as described in the README that the conversion result is not meant to be final working code, you need to go through all converted files and make sure they have a working as intended code.

**Comment by unirgy** [comment]
I've just pushed an update, to fix issue with converting consts - pull and rerun the conversion before proceeding please. Thanks

**Comment by Krupaly2k** [comment]
Hi Boris,

Thanks for the update. Also, please let me know if you have any good
solution for M1 to M2 theme migration.

Thanks in advance!

**Comment by unirgy** [comment]
The script moves the files into proper locations and updates the template files as best as it can.. The rest will have to be done manually.

**Comment by Krupaly2k** [comment]
Hi Boris,

I need some guidance to convert skin and theme folders from M1 to M2.
Please let me know if you have good solution for that.
