### ISSUE TITLE
Could not find a parent class file: /Users/alanstorm/Sites/magento-2-with-keys/app/code/Magento/Checkout/Controller/Cart/AbstractCart.php

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#5]
A module with the following controller

    #File: app/code/community/Pulsestorm/Converttest/controllers/CartLinkController.php
    <?php

    require_once Mage::getModuleDir('controllers','Mage_Checkout').DS.'CartController.php';

    class Pulsestorm_Converttest_CartlinkController extends Mage_Checkout_CartController
    {
        public function indexAction(){
            Mage::getSingleton('customer/session');
            Mage::helper('ometria_abandonedcarts/config');
            Mage::getModel('sales/quote')->load($id);
        }
    }
    
ends up producing the following cryptic warning

    [2015-12-05 08:11:52][INFO] EXTENSION: Pulsestorm_Converttest
    [2015-12-05 08:11:52][WARN] Could not find a parent class file: /Users/alanstorm/Sites/magento-2-with-keys/app/code/Magento/Checkout/Controller/Cart/AbstractCart.php (\Magento\Checkout\Controller\Cart\AbstractCart <- Pulsestorm\Converttest\Controller\CartLink\Index)
    [2015-12-05 08:11:52][SUCCESS] FINISHED: Pulsestorm_Converttest
    
While the specific example is a little contrived (`Pulsestorm_Converttest`), this is based on actual code from an actual Magento 1 module.

**Comment by astorm** [comment]
Looks like this one comes out of `_convertAllPhpFilesDI`

**Comment by unirgy** [comment]
I don't see how it's possible to automate this conversion, because in M1 controllers have all actions in 1 class, and in M2 they're all separated, and it's impossible to know which action class should be extended. 

In modules converted by the script I'm always generating an abstract class that actions are extending, but m2 core modules don't have this convention.

**Comment by astorm** [comment]
Got it, that makes sense. The only thing I'd suggest (and this is a pure project philosophy thing) would be detecting the error condition (your controller extends a core Magento controller) and give an appropriate error.  I got a little hung up assuming the problem was with the autoloder here -- better error messaging might have saved that.

**Comment by unirgy** [comment]
Please see if pushed solution is satisfiable

**Comment by astorm** [comment]
Thanks for the fix!

I don't have a great test harness setup for this and I'm in the middle of converting an extension (i.e. time constrained and can't afford to move my work out of the way to try reconverting).  Let's close it for now, and I've got a reminder setup to come back and test it when some time frees up.
