### ISSUE TITLE
Undefined offset: 5

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#6]
When running this on a set of modules that comprise a single extension (previously DM'd via twitter), I'm seeing the following notices

    PHP Notice:  Undefined offset: 5 in /Users/alanstorm/Documents/github/unirgy/convertm1m2/ConvertM1M2.php on line 1886
    PHP Stack trace:
    PHP   1. {main}() /Users/alanstorm/Documents/github/unirgy/convertm1m2/ConvertM1M2.php:0
    PHP   2. ConvertM1M2->convertAllExtensions() /Users/alanstorm/Documents/github/unirgy/convertm1m2/ConvertM1M2.php:48
    PHP   3. ConvertM1M2->_convertExtensionStage1() /Users/alanstorm/Documents/github/unirgy/convertm1m2/ConvertM1M2.php:316
    PHP   4. ConvertM1M2->_convertAllOtherFiles() /Users/alanstorm/Documents/github/unirgy/convertm1m2/ConvertM1M2.php:360
    PHP   5. ConvertM1M2->_convertPhpClasses() /Users/alanstorm/Documents/github/unirgy/convertm1m2/ConvertM1M2.php:1767
    PHP   6. ConvertM1M2->_convertCodeContents() /Users/alanstorm/Documents/github/unirgy/convertm1m2/ConvertM1M2.php:1798

**Comment by astorm** [comment]
This happens during the call to `_convertAllOtherFiles`

**Comment by astorm** [comment]
OK, tracked this down to [here](https://github.com/unirgy/convertm1m2/blob/master/ConvertM1M2.php#L1883)
        $classPattern = '#^((final|abstract)\s+)?class \\\\([A-Z][\\\\A-Za-z0-9]+)\\\\([A-Za-z0-9]+)((\s+)(extends|implements)\s|\s*$)?#ms';

        if (preg_match($classPattern, $contents, $m)) {
            $this->_currentFile['namespace'] = $m[3];
            $this->_currentFile['class'] = $m[3] . '\\' . $m[4];
            $contents  = str_replace($m[0], "namespace {$m[3]};\n\n{$m[1]}class {$m[4]}{$m[5]}", $contents);
        }

I'm still not sure I follow the context well enough, but it looks like that regex is supposed to match and parse the classname out of a file, but it doesn't for all files.  Here's a small example of how it doesn't work

    <?php
        $contents = file_get_contents('/Users/alanstorm/Desktop/science.txt');
        $contents = '<' . '?' . 'php' . "\n\n" . 
        'class \Foo\Core\Model\Observer\Cart {


        public function basketUpdated(\Magento\Framework\Event\Observer $observer){';
    
        $classPattern = '#^((final|abstract)\s+)?class \\\\([A-Z][\\\\A-Za-z0-9]+)\\\\([A-Za-z0-9]+)((\s+)(extends|implements)\s|\s*$)?#ms';

        preg_match($classPattern, $contents, $m);
        exit;    

The above program outputs

    array(5) {
      [0] =>
      string(35) "class \Foo\Core\Model\Observer\Cart"
      [1] =>
      string(0) ""
      [2] =>
      string(0) ""
      [3] =>
      string(23) "Foo\Core\Model\Observer"
      [4] =>
      string(4) "Cart"
    }

Unsure if this is a problem with the regex, or a problem with the state of the class being converted.

Looking at the RegEx -- is seems like there's an assumption that all classes will implement of extend something.  I'm not sure this is a safe assumption.  The example above (an Observers folder with individual Observers) is a common pattern I've seen in multiple extensions.  I've also seen other extensions drop in business logic only classes that don't extend anything.

**Comment by unirgy** [comment]
Thanks, in this case forgot that `preg_match` does not declare missing parts at the end of recognized pattern, fixed.

**Comment by astorm** [comment]
Fixed!
