### ISSUE TITLE
Unknown module key: blocks :: centinel

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#7]
Running this against Magento 1.9.2.2, I saw a lot of these messages during the `_collectCoreModulesLayouts` method call

    [2015-12-05 23:30:39][WARN] Unknown module key: blocks :: centinel
    [2015-12-05 23:30:39][WARN] Unknown module key: blocks :: centinel
    [2015-12-05 23:30:39][WARN] Unknown module key: blocks :: centinel

I took a look at the `Mage_Centinel` module and it looks like whatever team is behind Magento 1 maintenance has started leaving the `blocks`, `models`, and `helpers` nodes off their XML.  

    #File: app/code/core/Mage/Centinel/etc/config.xml
    <?xml version="1.0"?>
    <config>
        <modules>
            <Mage_Centinel>
                <version>1.6.0.0</version>
            </Mage_Centinel>
        </modules>
        <global>
            <events>
                <sales_convert_quote_to_order>
                    <observers>
                        <centinel>
                            <class>centinel/observer</class>
                            <method>salesEventConvertQuoteToOrder</method>
                        </centinel>
                    </observers>
                </sales_convert_quote_to_order>
                <checkout_submit_all_after>
                    <observers>
                        <centinel>
                            <class>centinel/observer</class>
                            <method>checkoutSubmitAllAfter</method>
                        </centinel>
                    </observers>
                </checkout_submit_all_after>
            </events>
        </global>
        <frontend>
            <translate>
                <modules>
                    <Mage_Centinel>
                        <files>
                            <default>Mage_Centinel.csv</default>
                        </files>
                    </Mage_Centinel>
                </modules>
            </translate>
            <events>
                <payment_form_block_to_html_before>
                    <observers>
                        <centinel>
                            <type>model</type>
                            <class>centinel/observer</class>
                            <method>paymentFormBlockToHtmlBefore</method>
                        </centinel>
                    </observers>
                </payment_form_block_to_html_before>
            </events>
            <routers>
                <centinel>
                    <use>standard</use>
                    <args>
                        <module>Mage_Centinel</module>
                        <frontName>centinel</frontName>
                    </args>
                </centinel>
            </routers>
            <layout>
                <updates>
                    <centinel>
                        <file>centinel.xml</file>
                    </centinel>
                </updates>
            </layout>
            <secure_url>
                <centinel>/centinel/</centinel>
            </secure_url>
        </frontend>
        <adminhtml>
            <events>
                <payment_info_block_prepare_specific_information>
                    <observers>
                        <centinel>
                            <type>model</type>
                            <class>centinel/observer</class>
                            <method>paymentInfoBlockPrepareSpecificInformation</method>
                        </centinel>
                    </observers>
                </payment_info_block_prepare_specific_information>
            </events>
            <translate>
                <modules>
                    <Mage_Centinel>
                        <files>
                            <default>Mage_Centinel.csv</default>
                        </files>
                    </Mage_Centinel>
                </modules>
            </translate>
            <layout>
                <updates>
                    <centinel>
                        <file>centinel.xml</file>
                    </centinel>
                </updates>
            </layout>
        </adminhtml>
        <admin>
             <routers>
                <adminhtml>
                    <args>
                        <modules>
                            <Mage_Centinel before="Mage_Adminhtml">Mage_Centinel_Adminhtml</Mage_Centinel>
                        </modules>
                    </args>
                </adminhtml>
            </routers>
        </admin>
        <global>
            <payment>
                <cc>
                    <types>
                        <VI>
                            <validator>
                                <centinel>
                                    <state>centinel/state_visa</state>
                                </centinel>
                            </validator>
                        </VI>
                        <MC>
                            <validator>
                                <centinel>
                                    <state>centinel/state_mastercard</state>
                                </centinel>
                            </validator>
                        </MC>
                        <JCB>
                            <validator>
                                <centinel>
                                    <state>centinel/state_jcb</state>
                                </centinel>
                            </validator>
                        </JCB>
                        <SM>
                            <validator>
                                <centinel>
                                    <state>centinel/state_mastercard</state>
                                </centinel>
                            </validator>
                        </SM>
                    </types>
                </cc>
            </payment>
        </global>
    </config>

Not sure if the conversion script should handle this in a hard coded way, or start inferring `Mage_` classes the same way Magento does for unknowns, but less noise in the logs is always nice.

**Comment by unirgy** [comment]
Since this is the only case in M1, i've hardcoded it.

**Comment by astorm** [comment]
Confirmed fixed!
