### ISSUE TITLE
Will Autoloader Work with Official Magento 2 Release

### ISSUE THREAD

**Issue by astorm** [unirgy/convertm1m2#9]
It looks like the autoloader callback adds two paths to the M2 code pool

    $m2Pools = [
        "{$this->_env['mage2_dir']}/lib/internal",
        "{$this->_env['mage2_code_dir']}",
    ];
    
Or, dumped out

    array(2) {
      [0] =>
      string(65) "/Users/alanstorm/Sites/magento-2-with-keys/magento2//lib/internal"
      [1] =>
      string(61) "/Users/alanstorm/Sites/magento-2-with-keys/magento2//app/code"
    }
    
Magento moved their core modules **out** of the `app/code` folder and into the `vendor/magento-*` folders, each with its own composer autoloader

    #File: vendor/magento/module-checkout/composer.json
    "autoload": {
        "files": [
            "registration.php"
        ],
        "psr-4": {
            "Magento\\Checkout\\": ""
        }
    }

It doesn't look like the autoloader callback will handle this?
    
(Sorry for the lack of a specific test here -- not sure when the autoloader is used in the program yet.)

**Comment by unirgy** [comment]
I may have to revisit this issue, for but for now added vendor modules autoload for stage 2

**Comment by unirgy** [comment]
Do you have any related actual error, or was it a hypothetical question?

**Comment by astorm** [comment]
A little of both?  I reported this when the system was yelling at me about all sorts of errors and I didn't understand how the program worked.  Now that I've spent a bit more time with the program I can't (at this moment) tie things back to a specific problem (since the conversion doesn't seem to autoload from Mage2?)

**Comment by unirgy** [comment]
Actually there's M2 autoload, by including `vendor/autoload.php` before collecting parent construct DI arguments (M2 classes), and for stage 2.

**Comment by unirgy** [comment]
Can we consider this issue closed?

**Comment by astorm** [comment]
Sure thing.  If it creates a problem I'll reopen.
